export default {
  languageData: [],
  notificationChannelIds: {},
  doctorAmount: "",
  dbName: 'HOPE',
  clicked: false,
  authExpired: false,
  inputType: '',
  zim: null,
  setMessageRefresh: false,
  inputValue: '',
  selectedCountryCode: '',
  fromCareCircle: "",
  userID: 0,
  patientID: 0,
  patientName: "",
  patientUserId: "",
  NR_Patient: "",
  diseaseID: 0,
  cachedData: {},
  appointmentType: "",
  userType: '',
  userInfo: {
    firstName: '',
    lastName: '',
    email: '',
    countryCode: '',
    mobileNo: '',
    gender: '',
    DOB: '',
    pincode: '',
    image: '',
    Biometric_Enabled: 'Enable',
    Device_Id: '',
    Address: ''
  },
  aadharDetails: {},
  nurseSelecting: {},
  nurseSearchData: [],
  DiseaseData: [],
  Biometric_UserId: '',
  Biometric_Id: '',
  appointmentDetails: [],
  patientList: [],
  patientDiseaseDetials: [],
  MedicineData: [],
  trustedDoctorDetails: [],
  trustedLabDetails: [],
  NurseappointmentDetails: [],
  VoiceSearchedData: [],
  selectedCycle: "",
  selectedDiseaseName: "",
  selectedTreatmentType: "",
  pageReadText: "",
  accessibility: {
    pageRead: false,
    imageDescription: false,
    textMagnifier: false,
    dictionary: false,
    readingMask: false,
    readingLine: false,
    enlargeButtons: false,
    reducedMotion: false,
    textAlignment: 'left', // 'left', 'center', 'right', 'justify'
  },
  messages: {
    "Rafael Whitehouse": [
      {
        id: 1,
        message: 'Was so great to see you!',
        time: "9:41",
        senderId: "sender",
        viewed: false,
      },
      {
        id: 2,
        message: 'We Should catch up soon!',
        time: "9:42",
        senderId: "sender",
      },
      {
        id: 3,
        message: `Let's get lunch soon! When aree you free? `,
        time: "10:01",
        senderId: "reciever",
      },
      {
        id: 4,
        message: `I'd love to see you!`,
        time: "10:02",
        senderId: "reciever",
      },
      {
        id: 5,
        message: `I'm in. Let's do it! 12:30 tommorow?`,
        time: "12:34",
        senderId: "sender",
      },
    ],
    "Jokubas Townsend": [
      {
        id: 1,
        message: 'Was so great 2 to see you!',
        time: "9:41",
        senderId: "sender",
        viewed: false,
      },
      {
        id: 2,
        message: 'We Should catch up soon!',
        time: "9:42",
        senderId: "sender",
      },
      {
        id: 3,
        message: `Let's get lunch soon! When aree you free? `,
        time: "10:01",
        senderId: "reciever",
      },
      {
        id: 4,
        message: `I'd love to see you!`,
        time: "10:02",
        senderId: "reciever",
      },
      {
        id: 5,
        message: `I'm in. Let's do it! 12:30 tommorow?`,
        time: "12:34",
        senderId: "sender",
      },
    ],
  },
  fontScale: 1,
  OS: "",
  authToken: 'authenticationtoken',
  androidVersion: 10,
  HoursIn24Format: [
    { value: "00" },
    { value: "01" },
    { value: "02" },
    { value: "03" },
    { value: "04" },
    { value: "05" },
    { value: "06" },
    { value: "07" },
    { value: "08" },
    { value: "09" },
    { value: "10" },
    { value: "11" },
    { value: "12" },
    { value: "13" },
    { value: "14" },
    { value: "15" },
    { value: "16" },
    { value: "17" },
    { value: "18" },
    { value: "19" },
    { value: "20" },
    { value: "21" },
    { value: "22" },
    { value: "23" },
  ],
  MinutesOptions: [
    { value: "00" },
    { value: "15" },
    { value: "30" },
    { value: "45" },
  ],
  doctorTransactionId: "",
  warningMessage: "Something went wrong, please try again"
};

